export const FETCH_MINASDEV_EVENTS_REQUEST = "MINASDEV/FETCH_MINASDEV_EVENTS_REQUEST";
export const FETCH_MINASDEV_EVENTS_SUCCESS = "MINASDEV/FETCH_MINASDEV_EVENTS_SUCCESS";
export const FETCH_MINASDEV_EVENTS_FAILURE = "MINASDEV/FETCH_MINASDEV_EVENTS_FAILURE";
