export const FETCH_MINASDEV_EVENTS_REQUEST = "MINASDEV/FETCH_MINASDEV_EVENTS_REQUEST";
export const FETCH_MINASDEV_EVENTS_SUCCESS = "MINASDEV/FETCH_MINASDEV_EVENTS_SUCCESS";
export const FETCH_MINASDEV_EVENTS_FAILURE = "MINASDEV/FETCH_MINASDEV_EVENTS_FAILURE";
export const FETCH_MINASDEV_JOBS_REQUEST = "MINASDEV/FETCH_MINASDEV_JOBS_REQUEST";
export const FETCH_MINASDEV_JOBS_SUCCESS = "MINASDEV/FETCH_MINASDEV_JOBS_SUCCESS";
export const FETCH_MINASDEV_JOBS_FAILURE = "MINASDEV/FETCH_MINASDEV_JOBS_FAILURE";
export const FILTER_MINASDEV_JOBS = "MINASDEV/FILTER_MINASDEV_JOBS";
